# Generated by Django 4.2.7 on 2023-11-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_alter_master_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='languages',
            field=models.CharField(choices=[('ru', 'Русский'), ('he', 'Иврит'), ('en', 'Английский')], default='ru', max_length=2, verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='master',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='master',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='master',
            name='pricemin',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Цена от'),
        ),
    ]
