# Generated by Django 4.2.7 on 2023-11-09 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPortfolioPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.city')),
                ('portfolio_photos', models.ManyToManyField(to='masters.masterportfoliophoto')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.service')),
            ],
        ),
    ]
