# Generated by Django 4.2.7 on 2023-11-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
