# Generated by Django 4.2.7 on 2023-11-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='price',
        ),
        migrations.AddField(
            model_name='master',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='master',
            name='pricemax',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Цена до'),
        ),
        migrations.AddField(
            model_name='master',
            name='pricemin',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Цена от'),
        ),
        migrations.AddField(
            model_name='master',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AddField(
            model_name='master',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
    ]
