# Generated by Django 4.2.7 on 2023-11-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_master_instagram_alter_master_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
