# Generated by Django 4.2.7 on 2023-11-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_master_languages_alter_master_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ru', 'Русский'), ('he', 'Иврит'), ('en', 'Английский')], max_length=20, unique=True, verbose_name='Язык')),
            ],
        ),
        migrations.AlterField(
            model_name='master',
            name='languages',
            field=models.BooleanField(choices=[('ru', 'Русский'), ('he', 'Иврит'), ('en', 'Английский')], default='ru', max_length=2, verbose_name='Языки'),
        ),
    ]
