# Generated by Django 4.2.7 on 2023-11-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_language_alter_master_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('ru', 'Русский'), ('he', 'Иврит'), ('en', 'Английский')], max_length=2, unique=True, verbose_name='Язык'),
        ),
        migrations.RemoveField(
            model_name='master',
            name='languages',
        ),
        migrations.AddField(
            model_name='master',
            name='languages',
            field=models.ManyToManyField(to='masters.language', verbose_name='Языки'),
        ),
    ]
