# Generated by Django 4.2.7 on 2023-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_remove_master_languages_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='languages',
            field=models.CharField(blank=True, choices=[('Hebrew', 'Иврит'), ('English', 'Английский')], max_length=100, null=True, verbose_name='Языки'),
        ),
    ]
