# Generated by Django 4.2.7 on 2023-11-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_alter_master_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='gallery',
            field=models.ImageField(default='', upload_to='media/masters', verbose_name='Фото ваших работ'),
            preserve_default=False,
        ),
    ]
