# Generated by Django 4.2.7 on 2023-11-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_master_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/masters/gallery', verbose_name='Фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='master',
            name='gallery',
        ),
        migrations.AddField(
            model_name='master',
            name='gallery',
            field=models.ManyToManyField(to='masters.galleryimage', verbose_name='Фото ваших работ'),
        ),
    ]
