# Generated by Django 4.2.7 on 2023-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0021_photo_remove_master_gallery_master_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='master',
            name='gallery',
            field=models.ImageField(default='', upload_to='media/masters/gallery', verbose_name='Фото ваших работ'),
            preserve_default=False,
        ),
    ]
