# Generated by Django 4.2.7 on 2023-11-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0022_remove_master_gallery_delete_photo_master_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profisrael/static/shop/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='master',
            name='gallery',
        ),
        migrations.AddField(
            model_name='master',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='work_img', to='masters.gallerypicture'),
        ),
    ]
