# Generated by Django 4.2.7 on 2023-11-20 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0023_gallerypicture_remove_master_gallery_master_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='gallery',
        ),
        migrations.AddField(
            model_name='gallerypicture',
            name='master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='masters.master', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='gallerypicture',
            name='image',
            field=models.ImageField(upload_to='profisrael/static/images/'),
        ),
    ]
