# Generated by Django 4.2.7 on 2023-11-23 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0023_alter_master_gallery_gallerypicture'),
        ('masters', '0024_remove_master_gallery_gallerypicture_master_and_more'),
    ]

    operations = [
    ]
