# Generated by Django 4.2.7 on 2023-11-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name_plural': 'Услуги'},
        ),
    ]
